### PR TITLE
fix: added Guy Fieri's blessing

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Description
Added [ASCII art of Guy Fieri because why not](https://github.com/nss-day-cohort-15/nss-day-cohort-15.github.io/pull/59/commits/792f3518a2550e17c6d99dfa019c5f44518d751e).

## Impacted Files in Application
script.js

## Deploy Notes

```sh
git pull --prune
git checkout hotfix-criticalBug
hs
```

View the script.js file on GitHub or clone it locally ¯\\_(ツ)_/¯

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM 🌮

**Comment by garrett-vangilder** [comment]
But really guys, I think this is very important for our class website.

**Comment by caseywreed** [comment]
My only question is why it isn't getting console.log'd

**Comment by matthamil** [comment]
@caseywreed Open a PR 🎉

**Pull request merged**
