### PR TITLE
Adding pics

### LINKED ISSUE #5: Add Pictures to ClassInfo.json
After Picture Day, we need to add each person's professional and "fun" picture to the img/ folder (maybe make a subdirectory).

Then, `classinfo.json` must be updated with the correct image link.

###Required Participants

- [ ] Matt Kraatz
- [ ] Matt Hamil
- [ ] Garrett Vangilder
- [ ] Liz Sanger
- [ ] Casey Reed
- [ ] Dayne Wright
- [ ] Debbie Bourne
- [ ] Delaine Wendling
- [ ] Jamie Duke
- [ ] Edgar Barajas
- [ ] Anulfo Ordaz
- [ ] Elliott Williams
- [ ] Fletcher Watson
- [ ] Meg Ducharme
- [ ] Tom Shavor
- [ ] Zack Repass
- [ ] Yonathon Molla
- [ ] Jacob Keen
- [ ] Jammy Laird
- [ ] Chris Smalley
- [ ] David Yunker
- [ ] Grant Regnier

Finally, the  tag `script.js` must be updated to reference the classinfo.json file instead of placeholder.it

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Description
Added all individual headshots, and inserted our fun group picture below the Technologies section. I also merged in Liz's branch so there wouldn't be any merge conflicts.

## Resolves Issue Number
Resolves #5 

## Impacted Files in Application
List general components of the application that this PR will affect:

* classinfo.json, index.html

## Deploy Notes

```sh
git pull --prune
git checkout addingPics
hs
```

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM! I noticed there is a link to the personality pictures, but theres no way to view them. Should we take them out so the site is more efficient?

**Comment by estorms** [comment]
My suggestion would be to keep the personality shots for now, in case we decide we want to integrate them at some point before demo day; if we don't, let's jettison them. I'm going to close my existing PR and checkout a branch to make two tweaks to this one (my and Delaine's prof pics got swapped for our personality shots), which otherwise LGTM! :) Thank you, @MattKraatz for rocking it out!

**Comment by MattKraatz** [comment]
@estorms I think that makes sense. For now, the fun pics won't impact loading or anything if they aren't linked from the index. Sorry for mixup haha!

**Comment by estorms** [comment]
@MattKraatz I just look so fetching with those binoculars ...

**Comment by matthamil** [comment]
Can we put the group photo as the background to the top section? I can't think of the CSS off the top of my head to stretch and cover a background, but that would make it fully responsive and fill the area. Currently, the image isn't responsive ;)

A `max-width` should be set on the images too to prevent stretching at different screen widths.

Also, David's linkedin needs to be prepended with "http://"

**Comment by MattKraatz** [comment]
@matthamil try this on for size.

Also, if anyone can figure out how to get rid of the rogue horizontal scrollbar that would be cool.

**Comment by estorms** [comment]
This looks good! @matthamil and @MattKraatz, I'll merge this branch and check out a new one to reintegrate the logic for displaying full names for those who included their middle, kill the scrollbar, and make all the images responsive. Are there any other final tweaks you can think of? I'll tackle those, too!

**Pull request merged**
