### PR TITLE
matt-styling-additions :: My take at styling

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Description
Hello all, here's my attempt at styling the cohort webpage.

I'm using placeholder images currently for avatars. HOWEVER, I think the colorscheme from the placeholder images is absolutely great! I think it'd be a good idea to incorporate those colors into the final website once everyone's pictures are loaded in correctly.

The top part of the webpage will be replaced with our group photo (with the text "Cohort 15" overlaying the photo). We might tint the black & white group photo blue-ish to keep with the color scheme.

NOTE: The "down arrow" in the top part of the page doesn't link to the next content area. If someone wants to add the necessary JS to make this happen, feel free to do so.

Should be 100% mobile responsive.

### PLEASE NOTE:

ALL JavaScript should be ES5. If you are using any ES6 features like `let`, `const`, arrow functions, etc, please transpile your ES6 to ES5 using a tool like [Babel](https://babeljs.io/). AFAIK some browsers like Safari will **not** run your JS if there is even a single `let` in your JS.

## Deploy Notes

```sh
git pull --prune
git checkout matt-styling-additions
http-server
```

Navigate to `localhost:8080` and let me know what you think.

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
Looks dope

**Comment by megducharme** [comment]
my computer won't let me get on your branch :( (not sure what's happening there), but I am sure it's great! :)

**Comment by MattKraatz** [comment]
Dude, awesome 👍

**Comment by flawavi** [comment]
very font. so colors.

**Comment by matthamil** [comment]
@megducharme Are you trying to check out the branch from a fork of this repo? You might need to update your forked repo or nuke/re-fork it if all else fails or clone the repo directly

**Comment by flawavi** [comment]
yeah i forked it originally and couldn't access your branch, so i cloned it down and boom.

**Comment by daynewright** [comment]
:shipit:

**Comment by estorms** [comment]
I think cloning is preferable because we're all members of the organization (?).

**Comment by estorms** [comment]
I'm going to merge! This is fantastic, @matthamil . Thank you!

**Pull request merged**
