### PR TITLE
Image styling fixes

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Description
Bugs:
* Individual images were being stretched to 100% of div width
* Class image was getting cut off on smaller screens

Solutions:
* Removed width attr on individual images and replaced with auto-centering
* Additional css rules to ensure LinkedIn icon displayed and all icons are aligned with images
* Added media queries to change height of header so background image isn't stretch so much

## Resolves Issue Number
Alternative solution to #53 

## Impacted Files in Application

* main.css

## Deploy Notes

```sh
git pull --prune
git checkout kraatz-pic-fix
hs
```

### CODE REVIEW

**Review by estorms — CHANGES_REQUESTED** [review]
This looks good! Do you want to kill the bouncing chevron on line 19 of `index.html`? We also need to be sure people with middle names have full names included. I hacked it by adding a space after everyone but Thom and Jamie Duke's last name in `classinfo.json` and replacing line 43 of `script.js` with the following `"<h3>" + person.name.split(" ")[0] + " " + person.name.split(" ")[1] + " " + person.name.split(" ")[2] + "</h3>" +"<hr>" +`. 

The image url in the `README` file also needs to be updated to `<div><a href="https://nss-day-cohort-15.github.io"></a></div>`

**Comment by MattKraatz** [comment]
@estorms I kinda like the chevron, especially since you can click on it and get that slow scroll. I could live without it, too, but my vote is to keep it.

Didn't notice the extra names, great catch! I added some conditional logic to domString to handle those two cases.

**Comment by daynewright** [comment]
@MattKraatz | @estorms  Looks good to me!! 👍   :shipit:

**Comment by estorms** [comment]
This is rad. Thank you, @MattKraatz! I'm gonna merge this puppy.

**Pull request merged**
